### PR TITLE
Generate css even on nested directory structure

### PR DESCRIPTION
**Pull request by gearsdigital**
I think it would be a nice addition if the css is also generated if the scss files are organized in a nested directory structure.

This change will look for file changes underneath `assets/scss`.

### CODE REVIEW

**Comment by bartvandebiezen** [comment]
Thank you for the pull request. Although it is a very nice feature, my concern is performance, because it is also active on live environments. What would be the performance hit when checking all segmented sass files every time and how could we make sure the performance doesn't become less? I am currently thinking about a 'dev setting'. But I am not sure yet.

**Comment by gearsdigital** [comment]
You're welcome :)

I never thought about performance but it's a valid point!

I'ld say (releated to performance) the best way might be to make use of a cache. As far as i know, `scssphp` is able to automatically create a `scss_cache` directory inside the stylesheets directory where it will store the compiled output. It should be not that hard to make use of the cache. What do you think?

http://leafo.github.io/scssphp/#quickstart

**Comment by bartvandebiezen** [comment]
Currently the plugin uses the final CSS output as cache. But when to update the 'cache' without doing it manually or activating a lot of checks...

**Comment by bartvandebiezen** [comment]
I have an idea I will try to implement.
1. You have to use multi-environment setup https://getkirby.com/blog/multi-environment-setup
2. For a dev environment you have to set 'scssNestedCheck' to 'true'.
3. This will make the main sass file 'touched' when a segmented sass file is newer than the main sass file. The check will be done every time you load a page.
4. Compiler is triggered as before. Even on a non-dev environment after you synced.

What do you think?

**Comment by bartvandebiezen** [comment]
I just added the feature as written down. You can now add `c::set('scssNestedCheck', true);` to the config of your dev environment.

**Pull request closed without merging**
